#!/usr/bin/env bash

date
set -x

# mount vbox shares...
#
mkdir share203
if mount | grep /share203 > /dev/null; then
    echo "its mounted"
else
    echo "not, so mount it"
	sudo mount -t vboxsf  share203 ~/share203
fi
#sudo mount -t vboxsf -o uid=$UID,gid=$(id -g) vamp203 ~/share203
#
sudo mkdir -p /var/www/html
if mount | grep /var/www/html > /dev/null; then
    echo "already mounted"
else
    echo "now mount it"
	sudo mount -t vboxsf  html /var/www/html
fi


echo endmntv

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


offlinestuff()  {

echo xxxx
}

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
date
#
