#!/usr/bin/env bash
#
date
set -x

# mount vbox shares...
#
mkdir share203
if mount | grep /share203 > /dev/null; then
    echo "its mounted"
else
    echo "not, so mount it"
	sudo mount -t vboxsf  share203 ~/share203
fi
#sudo mount -t vboxsf -o uid=$UID,gid=$(id -g) vamp203 ~/share203
#
sudo mkdir -p /var/www/html
if mount | grep /var/www/html > /dev/null; then
    echo "already mounted"
else
    echo "now mount it"
	sudo mount -t vboxsf  html /var/www/html
fi



echo end1

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


offlinestuff()  {

echo comment2
#begin comment --  http://stackoverflow.com/questions/947897/block-comments-in-a-shell-script
: <<'END'

sudo apt-get remove mysql-server phpmyadmin apache2


mkdir -p /var/www/html/cilist/templates_c
chmod 777 -r /var/www/html/cilist/templates_c
mkdir -p /var/www/html/leanmfg/templates_c

mkdir ~/share203
#sudo mount -t vboxsf -o uid=$UID,gid=$(id -g) share203 ~/share203
sudo mount -t vboxsf  share203 ~/share203
mkdir /var/www/html
sudo mount -t vboxsf  html /var/www/html

wget https://raw.githubusercontent.com/dgleba/vamp203/master/12bootstrap203.sh
wget https://raw.githubusercontent.com/dgleba/vamp203/master/15import203.sh
wget https://raw.githubusercontent.com/dgleba/vamp203/master/18django203.sh
wget https://raw.githubusercontent.com/dgleba/vamp203/master/90get.sh
wget https://raw.githubusercontent.com/dgleba/vamp203/master/start.sh
wget https://raw.githubusercontent.com/dgleba/vamp203/master/tmp1.sh


mkdir ~/share203
#sudo mount -t vboxsf -o uid=$UID,gid=$(id -g) vamp203 ~/share203
sudo mount -t vboxsf  share203 ~/share203
sudo mkdir -p /var/www/html
sudo mount -t vboxsf  html /var/www/html

END

}

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



#
date
#
