#!/usr/bin/env bash

#
set -x


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

saynow() {
date
}

offlinestuff()  {

#exit 8
sleep 7
echo offline
read offa

}

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

saynow
source ./12bootstrap203.sh
source ./15import203.sh
source ./18django203.sh
sudo reboot
date
